#!/usr/bin/env bash
#Installing nginx server
sudo apt update
sudo apt-get -y install nginx
sudo ufw allow http
sudo systemctl start nginx
echo "Holberton School for the win!" > /var/www/html/index.html
curl 127.0.0.1
