#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times

k=1
while [ $k -le 10 ]
do
    if [ $k -eq 4 ]
    then
	echo "bad luck"
    elif [ $k -eq 8 ]
    then
	echo "good luck"
    else
	echo "Holberton School"
    fi
((k++))
done
