#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times

hora=0
hora_max=12
while [ $hora -le $hora_max ]
do
    minutes=1
    echo "Hour: $hora"
    while [ $minutes -le 59 ]
    do
	echo "$minutes"
    ((minutes++))
    done
((hora++))
done
